### ISSUE TITLE
option for skipping content-type validation for GET request

### ISSUE THREAD

**Issue by waixwong** [exegesis-js/exegesis#105]
Some client library automatically adds a "content-type: application/json" header to all requests if such header is absent, which causes the api server to return "Invalid content-type: application/json" on GET requests. Since it doesn't make much sense to have a content-type header in get requests, is it possible to add an option to not validate content type for GET?

Thanks

**Comment by bymaximus** [comment]
Yes, Im also getting this issue, if the operation doest support/is not supposed to have 'Content-Type' according to OpenApi 
>GET, DELETE and HEAD are no longer allowed to have request body because it does not have defined semantics as per RFC 7231.

Those request methods should not check and validade request 'Content-Type'

https://github.com/exegesis-js/exegesis/blob/9345df6d81f907fa5e90257b288d22f043f6c6de/src/oas3/OpenApi.ts#L96-L101
