### ISSUE TITLE
Absolute paths in OpenAPI servers list are not parsed correctly

### ISSUE THREAD

**Issue by 7opf** [exegesis-js/exegesis#24]
In openapi.yaml, defining a server url like below is currently not working
```
servers:
  - url: '/api/0.1'
```
I have traced the bug to [this line](https://github.com/exegesis-js/exegesis/blob/master/src/oas3/Servers.ts#L59) where `basepath` should be set using `match[0]` instead of `match[1]`
That fixed it for me.

**Comment by borsucok** [comment]
Here is the temporary fix: you specify servers as:
- url: //api/v1/

I think the ABSOLUTE_URL_RE should be /^(\/.*)$/;
