### ISSUE TITLE
res.redirect not supported 

### ISSUE THREAD

**Issue by dshuang** [exegesis-js/exegesis#286]
Thanks for your work on this project.

res.redirect isn't supported, but origRes.redirect is.
What's the preferred way to handle redirects? 
Thanks.

**Comment by dshuang** [comment]
One solution: `res.writeHead(302, <redirect URL>) `

**Comment by kfichthorn** [comment]
I have the same issue....origRes.redirect works somewhat...except that 
Express passes the request along to our next middleware (which handles unmatched routes) because it thinks exegesis-middleware did not handle it.
