### ISSUE TITLE
PATCH method not supported

### ISSUE THREAD

**Issue by markusrydh** [exegesis-js/exegesis#33]
oas3/Path.js does not list PATCH among HTTP-methods:

const HTTP_METHODS = ['GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'CONNECT', 'OPTIONS', 'TRACE'];

This results in all paths with patch is ignored.

**Comment by jwalton** [comment]
Oops!  Thanks for pointing that out.  "CONNECT" shouldn't really be in there either - it's a valid HTTP method, but OpenAPI doesn't let you specify it in a [Path Item Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#path-item-object).

**Comment by jwalton** [comment]
Released in 1.0.4.

**Comment by markusrydh** [comment]
Super!
