### ISSUE TITLE
Confusing message when authenticator result type is `invalid`

### ISSUE THREAD

**Issue by niallmccullagh** [exegesis-js/exegesis#38]
## Version Info:

* node: 10.8.0
* exegesis-express: 1.0.5
* exegesis-express: 1.0.0
* express: 4.16.3

## Problem
I built a simple API to gain an understanding of your library. There is a single endpoint that is secured with the following scheme, which uses the sample authenticator that is detailed in [OAS3 Security.md](https://github.com/exegesis-js/exegesis/blob/master/docs/OAS3%20Security.md)

```
  securitySchemes:
    sessionKey:
      type: apiKey
      in: header
      name: session
```

When the `session` header is missing from the request the expected message is returned with a `401` status.

```bash
curl -i -X GET 'http://localhost:3000/v1/greet?name=ted'
HTTP/1.1 401 Unauthorized
content-type: application/json
Date: Fri, 31 Aug 2018 09:47:16 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"message":"Must authenticate using one of the following schemes: sessionKey."}
```

However, if the session header is specified but it is invalid, the same message is returned.

```bash
curl -i -X GET 'http://localhost:3000/v1/greet?name=ted' -H 'session: secret1'
HTTP/1.1 401 Unauthorized
content-type: application/json
Date: Fri, 31 Aug 2018 09:48:42 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"message":"Must authenticate using one of the following schemes: sessionKey."}
```

My initial conclusion was that the library was not detecting the session header, so I went digging into the code. I got down to the `authenticate` method on in `lib/oas3/Operation.js` and realised that it does detect the header, but noticed that it doesn't return the result if the security type is `invalid`.

I would've expected that the message and status code that I defined and returned in the authenticator to be set in the response.

For multiple authenticators, I would expect the behaviour to the same as a successful authentication. That is, it would return the result of the first invalid authenticator encountered.

**Comment by niallmccullagh** [comment]
I think the invalid credentials scenario is going to be more common with the scenario of multiple "credentials" being an edge case. The multiple credentials being passed would be also easier to spot from the request. 


> It's tempting to say we should reject immediately, but then, if you have a good basicAuth and a bad sessionKey ...  It's kind of weird that we pass in the one case, and fail in the other, just because the order of security requirements is different

That a very good point. Could this flow be a possible solution?

```
1. collect all invalids
1. return on the first success
1. If there was no success but one or more invalids then return an error listing the schemes(s) that were invalid `{message: "Authentication was invalid for the the following schemes: sessionKey."
 errors: [{scheme: result[x].failedSchemeName, message: result[x].message, ... }]  with the detailed messages of the invalid results 
}`
1. If all are missing then return `
{
    "message":"Must authenticate using one of the following schemes: sessionKey."
}`


I think the consumer of the API would have a clear understanding what occurred. An update to the developer documentation would be needed to call out that the order that the authenticators are run in and that the process is short-circuited on a success. 

> Maybe what we should really be doing here is not short-circuiting on success - always run all the authenticators, and if any of them returns "invalid" we fail. The only real downside to that is that exegesis-passport usually doesn't know the difference between a missing result and an invalid result, but so long as it errors on the side of "missing" it's not any worse than what we have now.

Agreed. The passport flow would be no worse than the current flow, but things would be improved for other integrations.

**Comment by jwalton** [comment]
Yes, although I'd suggest if there's at least one set of invalid credentials, we should still fail, even if there's also some valid passing credentials.  I'm working on something - hopefully I'll have a fix for this after the weekend.
