### ISSUE TITLE
Support for additional string formats

### ISSUE THREAD

**Issue by pawelusfr** [exegesis-js/exegesis#420]
OpenAPI spec allows for additional string formats like `uuid`, `email`, `ipv4`, `uri`, `hostname` etc. Right now `exegesis` is not validating those formats out of the box and it writes a warning about unknown format on init (warning comes from `ajv`).

It is possible to add those formats by getting them from `ajv-formats` and setting through `customFormats` option to exegesis.

Exegesis depends on `ajv-formats` already so it would be more convenient for downstream projects if `exegesis` included all formats from `ajv-formats` not just a subset.

**Comment by jwalton** [comment]
OpenAPI allows you to define whatever formats you want, but they don't specify what those formats are.  Your validation for an email address may be different than what someone else wants from an email address.  For example someone might have an "email" field in their schema that they explicitly don't want to validate, or which they want to validate but they want to ensure it ends in "mycorp.com".  As a result, I didn't want to add anything automatically beyond what's in the spec.
