### ISSUE TITLE
Mime-types

### ISSUE THREAD

**Issue by murithigeo** [exegesis-js/exegesis#449]
I'm building an application that predominantly interacts with GIS systems, therefore I need to use the `application/geo+json` mime type. However, I get this error `Unable to find suitable mime type parser for type application/geo+json`, despite its recognition, documentation and use in OGC API systems and documentation here.
It seems that exegesis does not also support the older `application/vnd.geo+json`

**Comment by murithigeo** [comment]
Noticed that application/geojson does not comply with the with [OAS Media Types](https://swagger.io/docs/specification/media-types/)

**Comment by jwalton** [comment]
If you're passing in a parameter of that type, Exegesis can handle it, but you'll need to specify [a parser](https://github.com/exegesis-js/exegesis/blob/master/docs/Options.md#mimetypeparsers) to figure out what to do with it (although the parser can be as simple as passing the data straight through if you want to handle it in your app).
