### ISSUE TITLE
Custom error format proposal

### ISSUE THREAD

**Issue by niallmccullagh** [exegesis-js/exegesis#47]
Hi Jason,

It would be great for developers using the library to be able to provide custom error formats. 

For example, I would like to provide data so that a front end could localize an error message in the browser user's locale or customise the message entirely.

I noticed that exegesis uses `Ajv` which provides a lot of data points. See [ajv#error-objects](https://github.com/epoberezkin/ajv#error-objects)

My thoughts are to:

1. Add more of these data points to `IValidationError` and set appropriately
1. Modify `src/core/exegesisRunner.ts#handleError` to maintain current format for backward compatibility.
1. Developers using the library could set `autoHandleHttpErrors` to false, catch and format the errors as they wish.

I would appreciate your feedback. I don't mind giving this a stab if you think it is a good idea.

Cheers,

Niall

**Comment by jwalton** [comment]
Yeah, go for it.  I have a [TODO here](https://github.com/exegesis-js/exegesis/blob/91aef7e633fa0a71b994ed8ed01f2adf62dafe91/src/core/exegesisRunner.ts#L80-L81) along these lines.  :)  I also need to handle localization at some point.

You could even add an `ajvError? : ajv.ValidationError` field to ValidationError with the original error object.

You could possibly optionally pass a `function(err)` for `autoHandleHttpErrors`?  Might be easier for consumers that way.

**Comment by niallmccullagh** [comment]
Closed by https://github.com/exegesis-js/exegesis/pull/50
