### ISSUE TITLE
Loading is too slow due to schema compilation

### ISSUE THREAD

**Issue by psznm** [exegesis-js/exegesis#496]
I am having issues with slow application startup which is caused by ajv.compile in this package.

I have around 100 api calls and the api loading takes me around 13 second which is 95% time of my application startup, if I exclude code-loading. 

I suggest that the schemas could be compiled lazily. I believe that would be very simple to implement, and to put behind an option. If you think that is a good idea, I am willing to implement this. Please, let me know if I should work on it.

**Comment by jwalton** [comment]
I’d definitely welcome a PR.

**Comment by psznm** [comment]
I have added PR solving this issue - https://github.com/exegesis-js/exegesis/pull/497
