### ISSUE TITLE
Feature Request: Generate a '405 - Method Not allowed' error

### ISSUE THREAD

**Issue by pvince** [exegesis-js/exegesis#71]
I am migrating a project from swagger-connect to exegesis-express.

If an endpoint is recognized, but the method is not swagger-connect will generate a 405 error message:
```
{
    "message": "Path [/items] defined in Swagger, but POST operation is not.",
    "statusCode": 405,
    "status": 405,
    "allowedMethods": [
        "GET"
    ],
    "code": "Method Not Allowed"
}
```

If I make the same request against my Exegesis server it is falling through to my 404 error handling.

**Comment by kf6kjg** [comment]
You can do this with a small plugin:
```js
{
	info: {
		name: "exegesis-plugin-route-405",
	},
	makeExegesisPlugin: (): ExegesisPluginInstance => ({
		postRouting: (context: ExegesisPluginContext): void => {
			if (context.api.pathItemPtr && !context.api.operationPtr) {
				// throw an error or respond how you wish.
			}
		},
	}),
},
```

I'm not 100% certain that the if-statement I used is the best, but it suffices for my tests thus far.

**Comment by jose-oliveira** [comment]
I think this should be fixed in the library itself, the current way isn't compatible with the OpenAPI specs. Created a PR to get the conversation started: https://github.com/exegesis-js/exegesis/pull/430
