### ISSUE TITLE
Can't pipe to context response

### ISSUE THREAD

**Issue by huydod** [exegesis-js/exegesis#90]
I use request module to stream a image from another source to context response as below

```
exports.getResourceByName = async context => {
  request('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png').pipe(context.res);
};
```

and get this error
```
TypeError: dest.on is not a function
    at Request.Stream.pipe (internal/streams/legacy.js:28:8)
    at Request.pipe (D:\br24\projects\cps\node_modules\request\request.js:1488:34)
    ...
```

it works with `res` from `express`

```
app.get('/google', (req, res) => {
  request('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png').pipe(res);
});
```

**Comment by jwalton** [comment]
You can just return a stream directly:

```js
exports.getResourceByName = async context => {
  return request('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png');
};
```

We should probably make it so `res` implements `WriteStream` so you can pipe to it.  But you can just return your stream, and Exegesis will take care of the rest.  :)

**Comment by huydod** [comment]
> You can just return a stream directly:
> 
> ```js
> exports.getResourceByName = async context => {
>   return request('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png');
> };
> ```
> 
> We should probably make it so `res` implements `WriteStream` so you can pipe to it. But you can just return your stream, and Exegesis will take care of the rest. :)

Thank you. It works for me now.
