### ISSUE TITLE
How to send a custom response on validation error?

### ISSUE THREAD

**Issue by ivan416** [exegesis-js/exegesis#97]
I'm trying to add a custom `onResponseValidationError` callback that sets the status to 400 and returns JSON containing validation errors.

Here is what I have so far:
```javascript
const options = {
    controllers: path.resolve(__dirname, './controllers'),
    allowMissingControllers: false,
    validateDefaultResponses: true,
    onResponseValidationError: (result) => {
      console.log("There is a validation error.");
      return result.context.res.status(400).json(result.errors);
    }
  };
```

However I keep getting this as the response:
```
{
  "message": "Trying to set status after response has been ended."
}
```

This is my controller for the reference:
```
exports.getGreeting = (context) => {
  const name = context.params.query.name;
  context.res
      .status(200)
      .setBody({invalidField: `Hello ${name}`});
}
```

I'm puzzled how to intercept regular controller flow on validation error and send a different response.

**Comment by jwalton** [comment]
I don't know that I ever intended `onResponseValidationError` to let you do what you're doing, but it's an interesting use case.

This check that's causing trouble is done in [`ExegesisResponseImpl`](https://github.com/exegesis-js/exegesis/blob/master/src/core/ExegesisResponseImpl.ts#L22-L24), and it happens after you've called `setBody()`.  The intent is to stop you from accidentally setting a body twice, and to sort of mimic the flow of an express response.  Here, though, it's just getting in the way.

We could reset `res.ended` to false right before calling into [onResponseValidationError()](https://github.com/exegesis-js/exegesis/blob/master/src/core/exegesisRunner.ts#L199).

As a temporary hacky workaround, you could do:

```js
    onResponseValidationError: (result) => {
      console.log("There is a validation error.");
      result.context.res.ended = false;
      return result.context.res.status(400).json(result.errors);
    }
```

**Comment by ivan416** [comment]
Thank you for the clarification!
